backends/open62541/src/import.c
fixes memleak when calling with a nullptr.
=> check arguments for open backend

src/Sort.c, tests/sort.c
this PR also refactors the cleaning up of the binary sorting tree. Now the nodes are cleaned up after sorting them, no matter if sorting was successful or fails. The cleanup is done via a recursion, if this leads to problems on large nodesets, the recursion should unrolled.
=> enable test with cycle detect again

backends/open62541/src/conversion.h
to get rid of the handwritten conversion routines.
Build only with the current master of open.
=> use UA_NodeId_parse from sdk

src/Value.c
The value passed to isspace must be representable as an
unsigned char (or EOF) according to the C99 standard. The
behavior for other values is undefined.
This could cause problems for char values > 127 depending on
the signedness of char.
=> Resolved undefined behavior for isspace

CMakeLists.txt
Properly installs libraries into architecture-specific directories on Debian-based systems.
=> cmake: use GNUInstallDirs

backends/open62541/src/DataTypeImporter.c
The switch field in a union shall not increment the member size
as no type is added for that field.
=> Switch field in unions shall not count as a member

backends/open62541/src/Value.c, backends/open62541/tests/namespaceZeroValues.c, backends/open62541/tests/namespaceZeroValues.xml
Guid values have not been supported yet. This PR adds them.
BTW. there are still a few standard DataTypes not supported. I will work next on Unions as I need them for my use case.
=> Support GUID values in the open62541 backend.

backends/open62541/src/import.c
E.g. Image was incorrectly flagged as a known type but subsequent calls to UA_findDataType() failed as Image isn't represented in UA_TYPES.
=> Limit known type range to built in types only

backends/open62541/src/Value.c
The enum value may either be on \<symbol\>_\<value\> or \<value\> format
depending on if it's part of a struct or not.
=> Enum value parsing now handling both possible formats

backends/open62541/CMakeLists.txt, backends/open62541/src/ServerContext.c, backends/open62541/src/ServerContext.h, backends/open62541/src/Value.c, backends/open62541/src/Value.h, backends/open62541/src/import.c, backends/open62541/tests/namespaceZeroValues.c, backends/open62541/tests/namespaceZeroValues.xml, backends/open62541/tests/subDataTypes.c
In Value.c there was a "TODO: translate namespaceIndex?"
In my opinion the answer should be yes. In my nodesets I'm having values that contain NodeIds, which are "poor man's references" to the nodes within the server (PubSub DataSet structures).
More details of the proposed change is included in the commit message. ServerContext.h includes some minimum documentation too.
=> Translate namespace indices in values.

backends/open62541/src/Value.c
- Importing a value works, if its DataType has been loaded through the NodesetCompiler before. (Trust me I tested it)
- Importing of union DataTypes from XML seems to still be broken.
Due to the above it's hard to make a unit test at the moment, as I can't get a DataType into the loader in the first place, without creating a dependency on open62541 code (to get the NodesetCompiler).
It would be useful to have a look in future at importing of union DataTypes.
=> Support values of union DataTypes.

backends/open62541/src/DataTypeImporter.c
NodesetCompiler in open62541 doesn't generate a DataType description struct unless the type has any members.
=> Fix an issue with loading structured DataTypes that are subtypes of abstract structures.

backends/open62541/src/Value.c
Statuscode variables have values stored as UInt32
=> feat(backends): Add support of StatusCode values

backends/open62541/src/Value.c
In some cases the structure size was not calculated correctly when reading setting its value. This becomes apparent when we're dealing with nested structures (or nested arrays of structures).
The size of a structure is not equal to the sum of its members. It's not enough to increment the offset after adding each member, the size of the whole structure needs to be considered
=> fix(backends): fixed struct size calculation when setting its value

nodesets/open62541/Opc.Ua.Di.NodeSet2_invalid_ordering.xml
This is a modified DI companion nodeset specification where the parent node with id **ns=1;i=15001** is defined after its child nodes:
- ns=1;i=15002
- ns=1;i=15003
- ns=1;i=15004
- ns=1;i=15005
- ns=1;i=15006
- ns=1;i=15007
- ns=1;i=15008
- ns=1;i=15031
- ns=1;i=15032
- ns=1;i=15033
This test XML is used for the ordering test case for open62541: [#5511](https://github.com/open62541/open62541/pull/5511)
=> build(open62541): DI Node ordering test case for open62541

backends/open62541/src/Value.c, backends/open62541/tests/CMakeLists.txt, backends/open62541/tests/issue_241.c, backends/open62541/tests/issue_241.xml
Fix https://github.com/open62541/open62541-nodeset-loader/issues/241 set value of statuscode. StatusCode itself is a complex type with a member _code_ which holds the uint32 statuscode.
=> add tests and fix issue_241

backends/open62541/src/DataTypeImporter.c
If an abstract data type is not checked properly, an error may occur later during processing if the abstract data type has no members (in function readyForMemsizeCalc).
For example, the error occurs when trying to load the FX data node set.
=> Properly check if it is an abstract type

.github/linters/.yaml-lint.yml, .github/workflows/ClangRelWithDebInfoAsan.yml, .github/workflows/GccDebugMemcheck.yml, .github/workflows/GccIntegrationTest.yml, .github/workflows/Linter.yml, .github/workflows/windows.yml
* enables workflow ClangRelWithDebInfoAsan.yml
*  adjusts the yamllint behavior due to the updated linter
TODO:
@NoelGraf please review and help if possible.
Kept the syling changes in separate commits for review, can be squashed later.
=> feat(ci): updates actions versions

backends/open62541/tests/dataTypeImport/CMakeLists.txt, backends/open62541/tests/integration/reference_server/CMakeLists.txt
* deprecated with https://github.com/open62541/open62541/pull/6214
* relates to https://github.com/open62541/open62541/pull/6307
ping @NoelGraf
=> [REVIEW] fix(tests): remove deprecated NAMESPACE_MAP from CMakeLists

backends/open62541/src/import.c
Support also old logger API from v1.3 and before.
This now also compiles with open62541 v1.3.
=> feat: compatibility with v1.3
