- .travis.yml
- backends/open62541/examples/server.c
- backends/open62541/src/import.c
- backends/open62541/tests/CMakeLists.txt
- backends/open62541/tests/newHierachicalRef.c
- backends/open62541/tests/newHierachicalRef.xml
- backends/open62541/tests/valueRank.xml
- src/nodeset.c
- src/nodeset.h
fixes https://github.com/matkonnerth/nodesetLoader/issues/26
> fix hierachicalRefs

- CMakeLists.txt
- backends/open62541/examples/dataTypeImport.c
- backends/open62541/src/import.c
- backends/open62541/tests/basicNodeClasses.xml
- backends/stdout/examples/main.c
- include/NodesetLoader/Logger.h
- include/NodesetLoader/NodesetLoader.h
- src/CharAllocator.c
- src/InternalLogger.h
- src/NodesetLoader.c
- src/PrintfLogger.c
openBackend uses this interfaces, passes the open logger to it.
> Add logging interface to nodesetLoader

- backends/open62541/src/import.c
this should solve the problem with the "duplicate" nodes
> use addNodeBegin for objects, variables and variableTypes

- backends/open62541/src/import.c
- backends/open62541/tests/nodeAttributes.c
- backends/open62541/tests/nodeAttributes.xml
- include/NodesetLoader/NodesetLoader.h
- src/Nodeset.c
- src/Nodeset.h
- src/NodesetLoader.c
- src/nodes/Node.c
this adds the non-hierachical refs after all nodes where added
> [WIP] Add nonhierachical refs

- include/NodesetLoader/NodesetLoader.h
- src/Nodeset.c
- src/Nodeset.h
- src/nodes/NodeContainer.c
- src/nodes/NodeContainer.h
This PR brings in logic to determine if a referenceType is hierachical or nonHierachical and considers this before adding nodes to sort.
> refactor hierachicalReference handling

- CMakeLists.txt
- src/Nodeset.c
- travis_script.sh
add flag to automated clang build with asan
> add flag for enabling asan

- backends/open62541/src/DataTypeImporter.c
fixes https://github.com/matkonnerth/nodesetLoader/issues/79
> fix memIssues

- backends/open62541/src/DataTypeImporter.c
- backends/open62541/tests/dataTypeImport/compareDITypes.c
- backends/open62541/tests/dataTypeImport/compareStructExtended.c
- backends/open62541/tests/dataTypeImport/compareStructSpecialized.c
- backends/open62541/tests/dataTypeImport/compareStructTypes.c
- backends/open62541/tests/testHelper.h
added tests for typename
comparison of memberTypeIds
> Refactoring dataTypeImport

- backends/open62541/src/RefServiceImpl.c
- backends/open62541/tests/references.c
- backends/open62541/tests/references.xml
- include/NodesetLoader/ReferenceService.h
- src/InternalRefService.c
- src/Nodeset.c
fixes https://github.com/matkonnerth/nodesetLoader/issues/61
> consider also subtypes of hasSubTypeRefs

- backends/open62541/src/import.c
- backends/stdout/examples/main.c
- include/NodesetLoader/NodesetLoader.h
- src/Nodeset.c
- src/Nodeset.h
- src/NodesetLoader.c
callback based interface, if we change the nodestore implementation in the future, client should not notice it.
> change interface of NodesetLoader for getting nodes

- backends/open62541/tests/integration/client/browse_utils.cpp
- backends/open62541/tests/integration/client/browse_utils.h
- backends/open62541/tests/integration/client/utils.cpp
- backends/open62541/tests/integration/reference_server/server.cpp
- backends/open62541/tests/integration/test_server/server.cpp
- nodesets/euromap/Opc.Ua.PlasticsRubber.GeneralTypes.NodeSet2.bsd
- nodesets/euromap/Opc.Ua.PlasticsRubber.GeneralTypes.NodeSet2.xml
DI and PLCopen tests work
DI_Euromap_83_77 test:
client gets bad read service result for node i=97 attribute UA_ATTRIBUTEID_DATATYPEDEFINITION
i=97 == OpcUaId_DataTypeDefinition
Afterwards referenceServer crashes
> DataTypeDefiniton attribute

- backends/open62541/src/Value.c
- backends/open62541/src/conversion.h
- backends/open62541/tests/CMakeLists.txt
- backends/open62541/tests/conversion.c
- conanfile.txt
fixes https://github.com/matkonnerth/nodesetLoader/issues/131
> remove strptime dependency

- CMakeLists.txt
- backends/open62541/examples/iterate.c
- backends/open62541/include/NodesetLoader/backendOpen62541.h
- backends/open62541/include/NodesetLoader/dataTypes.h
- include/NodesetLoader/arch.h
I am about to integrate the NodesetLoader into a Windows application
built in Visual Studio. This PR contains changes needed to make it
build properly and to get an .dll file as output.
I post the changes in one PR now for discussion and can split the changes into several PRs if needed.
> Updates to make it build on Windows with Visual Studio

- backends/open62541/src/import.c
- src/Nodeset.c
We observed crashes in various places when importing our nodesets which can be fixed easily via the attached commit.
> Fix potential NULL pointer dereferences

- .gitignore
- CMakeLists.txt
- backends/open62541/src/DataTypeImporter.c
- backends/open62541/src/Value.c
- backends/open62541/src/import.c
- backends/open62541/src/nodeset_base64.h
- backends/open62541/tests/dataTypeImport/CMakeLists.txt
- backends/open62541/tests/integration/CMakeLists.txt
- backends/open62541/tests/integration/reference_server/CMakeLists.txt
- backends/open62541/tests/integration/reference_server/server.cpp
Adding necessary support for integrating the nodesetLoader functionality within open62541 v1.3.2.
> [Review] Integration support for open62541 v1.3.2

- CMakeLists.txt
Compatibility layer for existing open62541 [v1.3.3](https://github.com/open62541/open62541/tree/v1.3.3).
> Add support for open62541 >= v1.3.2

- nodesets/open62541/testnodeset.xml
Regarding open62541 PR [#5414](https://github.com/open62541/open62541/pull/5414):
>        The test-nodeset could be hosted in the repo of the nodeset loader.
>
_Originally posted by @jpfr in https://github.com/open62541/open62541/pull/5414#discussion_r1012055762_
>
Because of that, added testnodeset.xml nodeset file within the nodesetLoader repository. This particular nodeset file is important since the same nodeset file is being used for testing the nodeset-compiler.
> feat(test): Add testnodeset.xml file for open62541 tests

- backends/open62541/tests/integration/reference_server/CMakeLists.txt
* relates to https://github.com/open62541/open62541/pull/5545
> fix(refactor): DI/NodeIds file renamed upstream

- backends/open62541/tests/basicNodeClasses.xml
> add object with string nodeId

- src/Nodeset.c
> Fixed default valuerank attribute parameter. Must be scalar.

- backends/open62541/src/import.c
- backends/open62541/tests/CMakeLists.txt
- backends/open62541/tests/primitiveValues.c
- backends/open62541/tests/primitiveValues.xml
- src/Value.c
fix for https://github.com/open62541/open62541-nodeset-loader/issues/239
> Fix segfault on empty value tag

- backends/open62541/src/DataTypeImporter.c
- backends/open62541/tests/CMakeLists.txt
- backends/open62541/tests/issue266_TestData.NodeSet2.xml
- backends/open62541/tests/issue_266_testdata.c
Handle UA_DataTypeKind_XmlElement in DataTypeImporter
add the test nodeset from repo https://github.com/OPCFoundation/UA-.NETStandard-Samples/Samples/Opc.Ua.Sample/TestData/TestData.NodeSet2.xml 
add test case
Fixes: https://github.com/open62541/open62541-nodeset-loader/issues/266
> Handle UA_DataTypeKind_XmlElement

- .github/workflows/GccDebugMemcheck.yml
- .github/workflows/GccIntegrationTest.yml
- .github/workflows/windows.yml
- CMakeLists.txt
- backends/open62541/tests/integration/CMakeLists.txt
is not necessary anymore, see windows.yml for cmake invocation with conan
> remove cmake option "EnableConan"

- backends/open62541/src/Value.c
Issue: https://github.com/open62541/open62541-nodeset-loader/issues/279
> Fixed functions for setting integer values.
